### PR TITLE
fix: added check to handle rare katakana writing (#18)

### LINKED ISSUE #18: Conversion problem with toRomaji function
When the toRomaji function is given katakana with the pattern "*ヮー" it throws the exception ```Null check operator used on a null value``` on [line 59 of the conversions.dart file](https://github.com/jeroen-meijer/kana_kit/blob/afd454d7447de9da92eceb128edb9cd0a3f3cd26/lib/src/conversions.dart#L59)

Two examples I encountered the problem with [シークヮーサー](https://jisho.org/word/%E3%82%B7%E3%83%BC%E3%82%AF%E3%83%AF%E3%83%BC%E3%82%B5%E3%83%BC) and [シマウヮー](https://jisho.org/word/%E5%B3%B6%E8%B1%9A)

### PR DESCRIPTION
**Pull request by Moseco**
Closes #18

### CODE REVIEW

**Comment by dariyooo** [comment]
@Moseco This is super useful, I encountered this today and this PR saved me from many hours of figuring out what's going on.

@jeroen-meijer can you please take a look at this PR and get it merged?

**Comment by HighLiuk** [comment]
Hey @jeroen-meijer how about this?
This bug is preventing the [JM Dict package](https://pub.dev/packages/jm_dict) from working

**Comment by jeroen-meijer** [comment]
Related to #18

**Comment by jeroen-meijer** [comment]
This issue should now be fixed in version 2.1.0, which has [just released](https://pub.dev/packages/kana_kit/versions/2.1.0).

**Pull request closed without merging**
